### ISSUE TITLE
Stopped working? Please fix

### ISSUE THREAD

**Issue by RkxBQ0Jyb3NUZXN0MUpTT04** [Sorrow446/ZS-DL#4]
It seems that it is having some problem in getting download URL now.

URL failed.
Exception: Failed to get file URL. Down?

For every URL in links.txt 
Please look into this. 
Worked like a charm for me for months but now it's not working...

**Comment by Sorrow446** [comment]
They changed their file URL JS. Fixed and pushed to src and binary.
