### ISSUE TITLE
Failed to get file URL. Down? 23/10/2020

### ISSUE THREAD

**Issue by chatchaiop** [Sorrow446/ZS-DL#5]
![image](https://user-images.githubusercontent.com/71642552/96955613-35c26080-1520-11eb-9bf1-e26aed88f654.png)

**Comment by Sorrow446** [comment]
Fixed https://github.com/Sorrow446/ZS-DL/commit/187580e9ed071835a33ecbd6bacd04205e4102d6.
Will push to Windows build soon.
